# Following Along with R

In this chapter we show you how to follow the book's examples with R. What is R? According to the R Project web's definition "R is a free software environment for statistical computing and graphics". In general we recommend you to work in an IDE like RStudio, that is a friendly user interface who allows you to have in view your workspace, output like graphics, help documentation, console, etc... This chapter doesn't intend to be comprehensive introduction to the language, instead is intended to provide you with the very basic tools to understand the development of the book excercises along the different chapters.  

If you want a widely comprehensive tutorial about `R` or specific topics like graphs or manipulating data, we recommend you the next free literature:  
- Wickham, H., Cetinkaya-Rundel, M. & Grolemund, G. (2023). R for data science. O'Reilly Media. 2nd Edition. [Link](https://r4ds.hadley.nz/)  
- Wickham, H. (2016). ggplot2: Elegant Graphics for Data Analysis, Springer-Verlag New York. [Link](https://ggplot2-book.org/)  
- Wilke, C. (2019). Fundamentals of Data Visualization: A Primer on Making Informative and Compelling Figures. O'Reilly Media. 1st Edition. [Link](https://clauswilke.com/dataviz/)  

The rest of this chapter is organized as follow: First is shown an introduction to the language as a tutorial focused in giving the tools to following along the book's material and procedures, next there is a series of sections focused on follow the book's examples and make the applications in R.