# Following Along with Stata

## Introduction

In this section we will provide a primer in [Stata](https://www.stata.com/), which seeks to provide you with the necessary tools to explore the microeconometric methods introduced throughout the book. "Stata is a complete, integrated software package that provides all your data science needs—data manipulation, visualization, statistics, and automated reporting" as is defined in its website. Stata has a long history, dating the middle 1980s, and also an ever-growing body of user-contributed add-on packages. It also has an active community providing online support on forums such as [Stata List](https://www.statalist.org/), and a substantial corpus of code online, meaning that large language models will be well suited to support you in your programming in Stata. It provides you with the large majority of tools you will need throughout this book, as well as the programming environment necessary to extend available tools where required.

The goal of this site is not to provide you with a comprehensive introduction to the software, but instead we it seeks to provide you with an overview of the basic tools to understand the required tools that we will use to get up and running in this book. In the first section we will focus on a brief rundown of some principal elements of Stata without yet getting into the empirical methods discussed in the textbook. Thereafter, we will focus on causal econometric methods, but in each section will also introduce any further tools required to complete key analyses or end-of-chapter questions. The goal of this resource is that after following along with these sections you will be sufficiently well-versed in Stata that you will comfortably be able to work with real data and econometric implementations. Nevertheless, below we point you to further resources if you are seeking a comprehensive overview of Stata as a software.

## Installing and Working with Stata

Information on how to order and get Stata is available on the [Stata website](https://www.stata.com/order/), and further support can be found searching the web. Stata also provide a user-friendly interface, allowing you to view any variable that you have generated in the memory in Stata, output like graphics, help documentation, and so forth. An example of what Stata looks like is provided below, where you can see that code is visible, as well as what is in the your "variables", a history of code and results window.  

AQUI PODRIAMOS INCLUIR UN PANTALLAZO DE STATA, QUIZAS PODRIA SER EL SUYO PROFESOR

## Further Resources

From here we will move to a first tutorial about Stata as a language, and an overview of a number of hey elements. If you are interested in generating a more complete overview of Stata, a number of resources can be consulted in the [Stata webpage](https://www.stata.com/links/).