<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Microeconometrics: Methods and Applications - 10&nbsp; Chapter 4</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./03_00_FollowingPython.html" rel="next">
<link href="./02_03_Chapter3Stata.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
    <div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-title">Chapter 4</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Microeconometrics: Methods and Applications</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/damiancclarke" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
    <a href="" title="Download" id="sidebar-tool-dropdown-0" class="sidebar-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false"><i class="bi bi-download"></i></a>
    <ul class="dropdown-menu" aria-labelledby="sidebar-tool-dropdown-0">
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Microeconometrics--Methods-and-Applications.pdf">
            <i class="bi bi-bi-file-pdf pe-1"></i>
          Download PDF
          </a>
        </li>
        <li>
          <a class="dropdown-item sidebar-tools-main-item" href="./Microeconometrics--Methods-and-Applications.epub">
            <i class="bi bi-bi-journal pe-1"></i>
          Download ePub
          </a>
        </li>
    </ul>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./index.html" class="sidebar-item-text sidebar-link">Introduction</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_01_About.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">About this book</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_02_Download.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">How to download the required data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./01_00_FollowingR.html" class="sidebar-item-text sidebar-link">Following Along with R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_01_IntroductionR.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">An Introduction to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_02_Chapter2R.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_03_Chapter3R.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_04_Chapter4R.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 4</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./02_00_FollowingStata.html" class="sidebar-item-text sidebar-link">Following Along with Stata</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_01_IntroductionStata.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">An Introduction to Stata</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_02_Chapter2Stata.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_03_Chapter3Stata.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_04_Chapter4Stata.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Chapter 4</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./03_00_FollowingPython.html" class="sidebar-item-text sidebar-link">Following Along with Python</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_01_IntroductionPython.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">An Introduction to Python</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_02_Chapter2Python.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 2</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_03_Chapter3Python.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 3</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_04_Chapter4Python.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Chapter 4</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_references.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#code-call-out-4.1" id="toc-code-call-out-4.1" class="nav-link active" data-scroll-target="#code-call-out-4.1">Code Call Out 4.1</a>
  <ul class="collapse">
  <li><a href="#the-two-way-fixed-effect-estimator" id="toc-the-two-way-fixed-effect-estimator" class="nav-link" data-scroll-target="#the-two-way-fixed-effect-estimator">The Two-way Fixed Effect Estimator</a></li>
  <li><a href="#goodmanbacon2018-decomposition" id="toc-goodmanbacon2018-decomposition" class="nav-link" data-scroll-target="#goodmanbacon2018-decomposition"><span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (2021)</span> Decomposition</a></li>
  <li><a href="#dechaisemartindhaultfoeuille2019s-procedure" id="toc-dechaisemartindhaultfoeuille2019s-procedure" class="nav-link" data-scroll-target="#dechaisemartindhaultfoeuille2019s-procedure"><span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (2020)</span>’s Procedure</a></li>
  </ul></li>
  <li><a href="#synthetic-control-exercise" id="toc-synthetic-control-exercise" class="nav-link" data-scroll-target="#synthetic-control-exercise">Synthetic Control Exercise</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title d-none d-lg-block"><span class="chapter-title">Chapter 4</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<div class="cell">

</div>
<section id="code-call-out-4.1" class="level2">
<h2 class="anchored" data-anchor-id="code-call-out-4.1">Code Call Out 4.1</h2>
<p><strong>Two-Way Fixed Effects Estimators and Heterogeneous Treatment Effects</strong> To understand the potential issues related to heterogeneous treatment effects over time and two-way fixed effect estimators, we will examine a pair of numerical examples. In particular, we will focus on the composition of the two way FE estimator <span class="math inline">\(\tau\)</span> estimated from: <span id="eq-twfe"><span class="math display">\[
y_{st} = \gamma_s + \lambda_t + \tau w_{st} + \varepsilon_{st}
\tag{10.1}\]</span></span> where <span class="math inline">\(y_{st}\)</span> is the outcome variable, <span class="math inline">\(\gamma_s\)</span> and <span class="math inline">\(\lambda_t\)</span> are state (unit) and time fixed effects, <span class="math inline">\(w_{st}\)</span> is the binary treatment variable that takes the value of 1 if a state (unit) <span class="math inline">\(s\)</span> is treated at time <span class="math inline">\(t\)</span> and otherwise takes 0. We will work with a quite tractable example based on three units and 10 time periods, and will document how the approaches taken by <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> and by <span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (<a href="06_references.html#ref-deChaisemartinDhaultfoeuille2019" role="doc-biblioref">2020</a>)</span> to understand the two-way FE estimator compare.</p>
<p>The results from <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> and those from <span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (<a href="06_references.html#ref-deChaisemartinDhaultfoeuille2019" role="doc-biblioref">2020</a>)</span> are similar, however they take quite different paths to get there. Goodman-Bacon’s (like that laid out in <span class="citation" data-cites="AtheyImbens2018">Athey and Imbens (<a href="06_references.html#ref-AtheyImbens2018" role="doc-biblioref">2022</a>)</span>) is “mechanical” in that it is based on the underlying difference-in-differences comparisons between all groups. The result in <span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (<a href="06_references.html#ref-deChaisemartinDhaultfoeuille2019" role="doc-biblioref">2020</a>)</span> is based on a potential outcomes frame-work, and counterfactuals under parallel trend assumptions. Thus to examine how these methods work requires somewhat different frameworks. In the case of <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span>, we should consider all possible DD comparisons, while in the case of <span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (<a href="06_references.html#ref-deChaisemartinDhaultfoeuille2019" role="doc-biblioref">2020</a>)</span> we should consider the treatment effect for each unit and time period, which requires knowing the observed and counterfactual state. While the approaches the two papers take to understand the content of the estimator differ, they refer to the same estimator, so always recover the same parameter estimate. To examine this in a more applied way, we will look at a simulated example.</p>
<p>To do this, let’s consider a panel of 3 states/areas over the 10 years (<span class="math inline">\(t\)</span>) of 2000 to 2009. One of these units is entirely untreated (<span class="math inline">\(unit = 1\)</span> or group <span class="math inline">\(U\)</span>), one is treated at an early time period, 2003, (<span class="math inline">\(unit = 2\)</span> or group <span class="math inline">\(k\)</span>), and the other is treated at a later time period, 2006, (<span class="math inline">\(unit = 3\)</span> or group <span class="math inline">\(l\)</span>). We will construct a general structure for this data below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="kw">obs</span> 30</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">obs</span>  = <span class="dt">_n</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> unit = <span class="fu">ceil</span>(<span class="kw">obs</span>/10)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="kw">bys</span> unit: <span class="kw">gen</span> <span class="fu">year</span> = <span class="dt">_n</span>+1999</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="ot">list</span> <span class="kw">in</span> 1/5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>number of observations (_N) was 0, now 30

     +-------------------+
     | obs   unit   year |
     |-------------------|
  1. |   1      1   2000 |
  2. |   2      1   2001 |
  3. |   3      1   2002 |
  4. |   4      1   2003 |
  5. |   5      1   2004 |
     +-------------------+</code></pre>
</div>
</div>
<p>We will consider a simple-case where the actual data-generating process is known as: <span class="math display">\[y_{unit,t} = 2 + 0.2 \times (t - 2000) + 1 \times unit + \beta_1 \times post \times unit + \beta_2 \times post \times unit \times (t - treat).\]</span> Here <span class="math inline">\(unit\)</span> refers to the unit number listed above (1, 2 or 3), <span class="math inline">\(post\)</span> indicates that a unit is receiving treatment in the relevant time period <span class="math inline">\(t\)</span>, and <span class="math inline">\(treat\)</span> refers to the treatment period (2003 for unit 2, and 2006 for unit 3). Let’s generate treatment, time to treatment, and post-treatment variables in <code>Stata</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> treat = 2006 <span class="kw">if</span> unit==2</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> treat = 2003 <span class="kw">if</span> unit==3</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> time = <span class="fu">year</span> - treat</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> <span class="kw">post</span> = time&gt;=0 &amp; time!=.</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> treat = 0 <span class="kw">if</span> treat==.</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> time  = 0 <span class="kw">if</span> time==.</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="kw">replace</span> <span class="kw">post</span>  = 0 <span class="kw">if</span> <span class="kw">post</span>==.</span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a><span class="ot">list</span> <span class="kw">in</span> 1/5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(20 missing values generated)

(10 real changes made)

(10 missing values generated)


(10 real changes made)

(10 real changes made)

(0 real changes made)

     +-----------------------------------------+
     | obs   unit   year   treat   time   post |
     |-----------------------------------------|
  1. |   1      1   2000       0      0      0 |
  2. |   2      1   2001       0      0      0 |
  3. |   3      1   2002       0      0      0 |
  4. |   4      1   2003       0      0      0 |
  5. |   5      1   2004       0      0      0 |
     +-----------------------------------------+</code></pre>
</div>
</div>
<p>This specification allows for each unit to have its own fixed effect, given that <span class="math inline">\(unit\)</span> is multiplied by 1, and allows for a general time trend increasing by 0.2 units each period across the whole sample. These parameters are not so important, as what we care about are the treatment effects themselves. The impact of treatment comes from the units <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span>. The first of these, <span class="math inline">\(\beta_1\)</span>, captures an immediate unit-specific jump when treatment is implemented which remains stable over time. The second of these, <span class="math inline">\(\beta_2\)</span>, implies a trend break occurring <em>only</em> for the treated units once treatment comes into place. We will consider 2 cases below. In the first case <span class="math inline">\(\beta_1 = 1\)</span> and <span class="math inline">\(\beta_2 = 0\)</span> (a simple case with a constant treatment effect per unit):</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> y1 = 2 + (<span class="fu">year</span> - 2000) * 0.2 + 1 * unit + 1 * <span class="kw">post</span> * unit + 0 * <span class="kw">post</span> * unit * time</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="ot">list</span> <span class="kw">in</span> 1/5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     | obs   unit   year   treat   time   post    y1 |
     |-----------------------------------------------|
  1. |   1      1   2000       0      0      0     3 |
  2. |   2      1   2001       0      0      0   3.2 |
  3. |   3      1   2002       0      0      0   3.4 |
  4. |   4      1   2003       0      0      0   3.6 |
  5. |   5      1   2004       0      0      0   3.8 |
     +-----------------------------------------------+</code></pre>
</div>
</div>
<p>and in a second case <span class="math inline">\(\beta_1 = 1\)</span> and <span class="math inline">\(\beta_2 = 0.45\)</span>. This is a more complex case in which there are heterogeneous treatment effects over time:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> y2 = 2 + (<span class="fu">year</span> - 2000) * 0.2 + 1 * unit + 1 * <span class="kw">post</span> * unit + 0.45 * <span class="kw">post</span> * unit * time</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="ot">list</span> <span class="kw">in</span> 1/5</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     | obs   unit   year   treat   time   post    y1    y2 |
     |-----------------------------------------------------|
  1. |   1      1   2000       0      0      0     3     3 |
  2. |   2      1   2001       0      0      0   3.2   3.2 |
  3. |   3      1   2002       0      0      0   3.4   3.4 |
  4. |   4      1   2003       0      0      0   3.6   3.6 |
  5. |   5      1   2004       0      0      0   3.8   3.8 |
     +-----------------------------------------------------+</code></pre>
</div>
</div>
<p>These two cases are plotted next where the line with empty circles refers to group <span class="math inline">\(U\)</span>, the line with black filled circles refers to group <span class="math inline">\(k\)</span> and the line with squares refers to group <span class="math inline">\(l\)</span></p>
<p><img src="docs/01_04_Chapter4R_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid"></p>
<section id="the-two-way-fixed-effect-estimator" class="level3">
<h3 class="anchored" data-anchor-id="the-two-way-fixed-effect-estimator">The Two-way Fixed Effect Estimator</h3>
<p>First we will estimate the parameter by two-way fixed effects regression. This will provide us with the parameter estimate that both <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> and <span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (<a href="06_references.html#ref-deChaisemartinDhaultfoeuille2019" role="doc-biblioref">2020</a>)</span> will construct in a piece-wise fashion. This is done relatively simply in <code>R</code>. We simply estimate <a href="03_04_Chapter4Python.html#eq-twfe">Equation&nbsp;<span>14.1</span></a> by linear regression using <code>lm</code> as laid out below:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> y1 i.unit i.<span class="fu">year</span> <span class="kw">post</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="kw">as</span> <span class="bn">text</span> <span class="st">"The parameter estimates by two-way fixed effects regression for the case 1 is: "</span> _b[<span class="kw">post</span>]</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> y2 i.unit i.<span class="fu">year</span> <span class="kw">post</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="kw">as</span> <span class="bn">text</span> <span class="st">"The parameter estimates by two-way fixed effects regression for the case 2 is: "</span> _b[<span class="kw">post</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>The parameter estimates by two-way fixed effects regression for the case 1 is: 
&gt; 2.4545456


The parameter estimates by two-way fixed effects regression for the case 2 is: 
&gt; 3.8045454</code></pre>
</div>
</div>
<p>Here we see that the coefficient of interest is 2.454545. We can see that this is between the two unit-specific jumps that occur with treatment (2 and 3). We will see below why it takes this particular weighted average.</p>
</section>
<section id="goodmanbacon2018-decomposition" class="level3">
<h3 class="anchored" data-anchor-id="goodmanbacon2018-decomposition"><span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> Decomposition</h3>
<p>Using the values simulated above, let’s see how the <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> decomposition allows us to understand estimated treatment effects. We will consider both:<br>
- (a) Simple Decomposition<br>
- (b) Decomposition with trends</p>
<p>The methodology <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> decomposition suggests that we should calculate all <span class="math inline">\(2 \times 2\)</span> combinations of states and time where post-treatment units are compared to “untreated” unit (laid out at more length in the boo). In this example, this provides four specific effects, which contribute to <span class="math inline">\(\widehat{\tau}\)</span> as a weighted mean. The specific effects desired are:</p>
<ul>
<li>A. <span class="math inline">\(\widehat{\beta}^{2\times2}_{kU}\)</span> from the comparison of the early treated unit with the untreated unit.<br>
</li>
<li>B. <span class="math inline">\(\widehat{\beta}^{2\times2}_{lU}\)</span>, from the comparison of the latter treated unit with the untreated unit.<br>
</li>
<li>C. <span class="math inline">\(\widehat{\beta}^{2\times2,k}_{kl}\)</span>, from the comparison of the early and latter treated units, when the early unit begin to be treated.<br>
</li>
<li>D. <span class="math inline">\(\widehat{\beta}^{2\times2,l}_{kl}\)</span>, from the comparison of the early and latter treated units, when the latter unit begin to be treated.</li>
</ul>
<p>These will then be weighted as laid out in <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> to provide the regression-based estimate.</p>
<section id="a-simple-decomposition" class="level4">
<h4 class="anchored" data-anchor-id="a-simple-decomposition">(a) Simple Decomposition</h4>
<p>In this case the <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> methodology estimate <span class="math inline">\(\widehat{\tau}\)</span> weighting the next four DD comparisons</p>
<p><img src="docs/01_04_Chapter4R_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid"></p>
<p>As seen in the plots, in the simple decomposition these effects are constants of 3 and 2 for early and later treated units given that the “treatment effect” is simply <span class="math inline">\(1 \times unit\)</span> in each case.</p>
<section id="a.-early-group-vs-untreated-group" class="level5">
<h5 class="anchored" data-anchor-id="a.-early-group-vs-untreated-group">A. Early Group v/s Untreated Group</h5>
<p>In order to calculate the effects we start making the simple DD comparison of the untreated group <span class="math inline">\(U\)</span> (<span class="math inline">\(unit = 1\)</span>) with the early treated group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>) getting <span class="math inline">\(\widehat{\beta}^{2 \times 2}_{kU}\)</span> as <span class="math display">\[\widehat{\beta}^{2 \times 2}_{kU} = \left( \overline{y}_k^{Post(k)} - \overline{y}_k^{Pre(k)} \right) - \left( \overline{y}_U^{Post(k)} - \overline{y}_U^{Pre(k)} \right)\]</span> Where <span class="math inline">\(\overline{y}_k^{Post(k)}\)</span> is the mean of the outcome variable for the early treated group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>) posterior to treatment, from 2003, <span class="math inline">\(\overline{y}_k^{Pre(k)}\)</span> is the mean for of the outcome variable for the early treated group <span class="math inline">\(U\)</span> (<span class="math inline">\(unit = 3\)</span>) prior to treatment, (up until 2002), and <span class="math inline">\(\overline{y}_U^{Post(k)}, \overline{y}_U^{Post(k)}\)</span> are the analogous quantities for the untreated group <span class="math inline">\(U\)</span> (<span class="math inline">\(unit = 1\)</span>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 3 &amp; <span class="kw">post</span> == 1</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1treatmeanpost = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 3 &amp; <span class="kw">post</span> == 0</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1treatmeanpre = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> dify1treat = y1treatmeanpost - y1treatmeanpre</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 1 &amp; <span class="fu">year</span> &gt;= 2003</span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1controlmeanpost = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 1 &amp; <span class="fu">year</span> &lt; 2003</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1controlmeanpre = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> dify1control = y1controlmeanpost - y1controlmeanpre</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="kw">as</span> result <span class="fu">round</span>(dify1treat - dify1control, 0.01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>3</code></pre>
</div>
</div>
<p>This result also can be obtained from the linear regression with the canonical DD formula <span class="math display">\[y_{unit,t} = \alpha_0 + \alpha_1 \times Post(k) + \alpha_2 \times \mathbf{1}(unit = 3) + \beta_{kU}^{2\times2} \times Post(k) \times \mathbf{1}(unit = 3) + \varepsilon_i\]</span> Where <span class="math inline">\(Post(k)\)</span> indicates that the year is equal or greater than the year where the group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>) received the treatment (2003) and <span class="math inline">\(\mathbf{1}(unit = 3)\)</span> indicates if the observation is from the early treated group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> post2003 = (<span class="fu">year</span> &gt;= 2003)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> y1 i.post2003 i.unit i.post2003#i.unit <span class="kw">if</span> unit != 2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Source |       SS           df       MS      Number of obs   =        20
-------------+----------------------------------   F(3, 16)        =    266.11
       Model |  119.750004         3  39.9166679   Prob &gt; F        =    0.0000
    Residual |  2.40000019        16  .150000012   R-squared       =    0.9804
-------------+----------------------------------   Adj R-squared   =    0.9767
       Total |  122.150004        19  6.42894757   Root MSE        =     .3873

------------------------------------------------------------------------------
          y1 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
  1.post2003 |   .9999999   .2672613     3.74   0.002     .4334314    1.566568
      3.unit |          2   .3162278     6.32   0.000     1.329627    2.670373
             |
    post2003#|
        unit |
        1 3  |          3   .3779645     7.94   0.000     2.198751    3.801249
             |
       _cons |        3.2   .2236068    14.31   0.000     2.725975    3.674025
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>A third way to obtain this is from the next linear regression <span class="math display">\[y_{unit,t} = \alpha_0 + \beta_{kU}^{2 \times 2} \times Post + \sum_{i = 2001}^{2009} \alpha_{i-2000} \times \mathbf{1}(year = i) + \alpha_{10} \times \mathbf{1}(unit = 3) + \varepsilon_i\]</span> Where in this case <span class="math inline">\(Post\)</span> indicates if the unit is treated (note for group <span class="math inline">\(U\)</span> this will be always 0), <span class="math inline">\(\mathbf{1}(year = i)\)</span> indicates if the observation is in period <span class="math inline">\(i \in \{2001, \ldots, 2009\}\)</span> and <span class="math inline">\(\mathbf{1}(unit = 3)\)</span> keep its meaning</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> y1 <span class="kw">post</span> i.<span class="fu">year</span> i.unit <span class="kw">if</span> unit != 2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Source |       SS           df       MS      Number of obs   =        20
-------------+----------------------------------   F(11, 8)        =         .
       Model |  122.150004        11  11.1045458   Prob &gt; F        =         .
    Residual |           0         8           0   R-squared       =    1.0000
-------------+----------------------------------   Adj R-squared   =    1.0000
       Total |  122.150004        19  6.42894757   Root MSE        =         0

------------------------------------------------------------------------------
          y1 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
        post |          3          .        .       .            .           .
             |
        year |
       2001  |   .1999999          .        .       .            .           .
       2002  |   .4000001          .        .       .            .           .
       2003  |   .6000001          .        .       .            .           .
       2004  |         .8          .        .       .            .           .
       2005  |   .9999999          .        .       .            .           .
       2006  |        1.2          .        .       .            .           .
       2007  |        1.4          .        .       .            .           .
       2008  |        1.6          .        .       .            .           .
       2009  |        1.8          .        .       .            .           .
             |
      3.unit |          2          .        .       .            .           .
       _cons |          3          .        .       .            .           .
------------------------------------------------------------------------------</code></pre>
</div>
</div>
<p>Now we store this result for posterior use</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> bku = _b[<span class="kw">post</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="b.-later-group-vs-untreated-group" class="level5">
<h5 class="anchored" data-anchor-id="b.-later-group-vs-untreated-group">B. Later Group v/s Untreated Group</h5>
<p>The next DD comparison we calculate is that which compares the later treated group <span class="math inline">\(l\)</span> (<span class="math inline">\(unit = 2\)</span>) with the untreated group <span class="math inline">\(U\)</span> (<span class="math inline">\(unit = 1\)</span>), resulting in <span class="math inline">\(\widehat{\beta}^{2 \times 2}_{lU}\)</span>. As above, we can generate this DD estimate in a number of ways (most simply by double-differencing with means), and this will then be stored.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 2 &amp; <span class="kw">post</span> == 1</span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1treatmeanpost = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 2 &amp; <span class="kw">post</span> == 0</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1treatmeanpre = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> dify1treat = y1treatmeanpost - y1treatmeanpre</span>
<span id="cb18-6"><a href="#cb18-6" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 1 &amp; <span class="fu">year</span> &gt;= 2006</span>
<span id="cb18-7"><a href="#cb18-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1controlmeanpost = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb18-8"><a href="#cb18-8" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> y1 <span class="kw">if</span> unit == 1 &amp; <span class="fu">year</span> &lt; 2006</span>
<span id="cb18-9"><a href="#cb18-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> y1controlmeanpre = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb18-10"><a href="#cb18-10" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> dify1control = y1controlmeanpost - y1controlmeanpre</span>
<span id="cb18-11"><a href="#cb18-11" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> blu = dify1treat - dify1control</span>
<span id="cb18-12"><a href="#cb18-12" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="kw">as</span> result <span class="fu">round</span>(blu, 0.01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2</code></pre>
</div>
</div>
</section>
<section id="c.-early-group-vs-later-group-before-2006" class="level5">
<h5 class="anchored" data-anchor-id="c.-early-group-vs-later-group-before-2006">C. Early Group v/s Later Group Before 2006</h5>
<p>Next we calculate the effects from the DD comparisons of early and later treated groups, up until the later treated group receives treatment (2006). This is: <span class="math display">\[\widehat{\beta}^{2 \times 2, k}_{kl} \equiv \left( \overline{y}^{Mid(k,l)}_{k} - \overline{y}^{Pre(k)}_{k} \right) - \left( \overline{y}^{Mid(k,l)}_{l} - \overline{y}^{Pre(k)}_{l} \right)\]</span> where <span class="math inline">\(\overline{y}^{Mid(k,l)}_{k}\)</span> is the mean of the outcome variable for the early treated group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>) in the period between the treatment for the group <span class="math inline">\(k\)</span> and the group <span class="math inline">\(l\)</span> (<span class="math inline">\(unit = 2\)</span>), from 2003 to 2005, <span class="math inline">\(\overline{y}^{Pre(k)}_{k}\)</span> is the mean for of the outcome variable for the early treated group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>) previous to treatment, until 2002, and <span class="math inline">\(\overline{y}^{Mid(k,l)}_{l}, \overline{y}^{Pre(k)}_{l}\)</span> are the analogous for the later treated group <span class="math inline">\(l\)</span> (<span class="math inline">\(unit = 2\)</span>)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> y1 <span class="kw">post</span> i.<span class="fu">year</span> i.unit <span class="kw">if</span> unit != 1 &amp; <span class="fu">year</span> &lt; 2006</span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> bklk = _b[<span class="kw">post</span>]</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="fu">round</span>(bklk, 0.01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Source |       SS           df       MS      Number of obs   =        12
-------------+----------------------------------   F(7, 4)         =         .
       Model |  39.0500037         7  5.57857195   Prob &gt; F        =         .
    Residual |           0         4           0   R-squared       =    1.0000
-------------+----------------------------------   Adj R-squared   =    1.0000
       Total |  39.0500037        11  3.55000033   Root MSE        =         0

------------------------------------------------------------------------------
          y1 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
        post |          3          .        .       .            .           .
             |
        year |
       2001  |   .1999998          .        .       .            .           .
       2002  |   .4000001          .        .       .            .           .
       2003  |   .6000001          .        .       .            .           .
       2004  |   .8000001          .        .       .            .           .
       2005  |   .9999999          .        .       .            .           .
             |
      3.unit |          1          .        .       .            .           .
       _cons |          4          .        .       .            .           .
------------------------------------------------------------------------------


3</code></pre>
</div>
</div>
</section>
<section id="d.-early-group-vs-later-group-after-2003" class="level5">
<h5 class="anchored" data-anchor-id="d.-early-group-vs-later-group-after-2003">D. Early Group v/s Later Group After 2003</h5>
<p>The last DD comparison is for early and later treated groups, starting from 2006 <span class="math display">\[\widehat{\beta}^{2 \times 2, l}_{kl} \equiv \left( \overline{y}^{Post(l)}_{l} - \overline{y}^{Mid(k,l)}_{l} \right) - \left( \overline{y}^{Post(l)}_{k} - \overline{y}^{Mid(k,l)}_{k} \right)\]</span> Where <span class="math inline">\(\overline{y}^{Post(l)}_{l}\)</span> is the mean of the outcome variable for the later treated group <span class="math inline">\(l\)</span> (<span class="math inline">\(unit = 2\)</span>) in the period after this group received the treatment, from 2006, <span class="math inline">\(\overline{y}^{Mid(k,l)}_{l}\)</span> is the mean for of the outcome variable for the later treated group <span class="math inline">\(l\)</span> (<span class="math inline">\(unit = 2\)</span>) in the period between the treatment for the group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>) and the group <span class="math inline">\(l\)</span>, from 2003 to 2005, and <span class="math inline">\(\overline{y}^{Post(l)}_{k}, \overline{y}^{Mid(k,l)}_{k}\)</span> are the analogous quantities for the early treated group <span class="math inline">\(k\)</span> (<span class="math inline">\(unit = 3\)</span>). We can generate and save this quantity as we have previously:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb22"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="kw">reg</span> y1 <span class="kw">post</span> i.<span class="fu">year</span> i.unit <span class="kw">if</span> unit != 1 &amp; <span class="fu">year</span> &gt; 2002</span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> bkll = _b[<span class="kw">post</span>]</span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> <span class="fu">round</span>(bkll, 0.01)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Source |       SS           df       MS      Number of obs   =        14
-------------+----------------------------------   F(8, 5)         =         .
       Model |  42.4685725         8  5.30857156   Prob &gt; F        =         .
    Residual |           0         5           0   R-squared       =    1.0000
-------------+----------------------------------   Adj R-squared   =    1.0000
       Total |  42.4685725        13  3.26681327   Root MSE        =         0

------------------------------------------------------------------------------
          y1 |      Coef.   Std. Err.      t    P&gt;|t|     [95% Conf. Interval]
-------------+----------------------------------------------------------------
        post |          2          .        .       .            .           .
             |
        year |
       2004  |         .2          .        .       .            .           .
       2005  |   .3999999          .        .       .            .           .
       2006  |   .5999996          .        .       .            .           .
       2007  |   .7999996          .        .       .            .           .
       2008  |   .9999999          .        .       .            .           .
       2009  |        1.2          .        .       .            .           .
             |
      3.unit |          2          .        .       .            .           .
       _cons |        4.6          .        .       .            .           .
------------------------------------------------------------------------------


2</code></pre>
</div>
</div>
<p>This comparison is the comparison which can potentially result in undesired results if treatment effects are dynamic over time because it views group 3 (the previously treated group) as a control. However, in this case, given that treatment effects are homogenous over time we do not have a major problem here, and we observe that <span class="math inline">\(\widehat{\beta}^{2 \times 2, l}_{kl}=2\)</span>.</p>
</section>
<section id="weights" class="level5">
<h5 class="anchored" data-anchor-id="weights">Weights</h5>
<p>We can now arrive to the OLS estimate of this two-way fixed effect model by generating the weighted mean of the previous estimates as: <span class="math display">\[\widehat{\tau} = W_{kU} \cdot \widehat{\beta}^{2\times 2}_{kU} + W_{lU} \cdot \widehat{\beta}^{2\times 2}_{lU} + W_{kl}^{k} \cdot \widehat{\beta}^{2\times 2,k}_{kl} + W_{kl}^{l} \cdot \widehat{\beta}^{2\times 2,l}_{kl}\]</span> Where each <span class="math inline">\(W\)</span> is the weight that the respective <span class="math inline">\(\beta\)</span> has in this weighted mean, specifically: <span class="math display">\[\begin{align*}
W_{kU} &amp; = \frac{(n_k + n_U)^2\widehat{V}^D_{kU}}{\widehat{V}^D} \quad &amp;  \quad W_{lU} &amp; = \frac{(n_l + n_U)^2\widehat{V}^D_{lU}}{\widehat{V}^D} \\
W_{kl}^k &amp; = \frac{[(n_k + n_l)(1 - \overline{D}_l)]^2\widehat{V}^{D,k}_{kl}}{\widehat{V}^D} \quad &amp;  \quad W_{kl}^l &amp; = \frac{[(n_k + n_l)(1 - \overline{D}_k)]^2\widehat{V}^{D,l}_{kl}}{\widehat{V}^D}
\end{align*}\]</span> Where <span class="math inline">\(n\)</span> refers to the sample share of the group</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> nk = 1/3</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> <span class="kw">nl</span> = 1/3</span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> nu = 1/3</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><span class="math inline">\(\overline{D}\)</span> referes to the share of time the group is treated</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> <span class="kw">post</span> <span class="kw">if</span> unit == 3</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Dk = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> <span class="kw">post</span> <span class="kw">if</span> unit == 2</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Dl = <span class="fu">r</span>(<span class="kw">mean</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>and <span class="math inline">\(\widehat{V}\)</span> refers to how much treatment varies</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> <span class="kw">post</span> <span class="kw">if</span> unit == 3</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Dk = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb26-3"><a href="#cb26-3" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> <span class="kw">post</span> <span class="kw">if</span> unit == 2</span>
<span id="cb26-4"><a href="#cb26-4" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Dl = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb26-5"><a href="#cb26-5" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> VkU = 0.5*0.5*(Dk)*(1-Dk)</span>
<span id="cb26-6"><a href="#cb26-6" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> VlU = 0.5*0.5*(Dl)*(1-Dl)</span>
<span id="cb26-7"><a href="#cb26-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Vklk = 0.5*0.5*((Dk-Dl)/(1-Dl))*((1-Dk)/(1-Dl))</span>
<span id="cb26-8"><a href="#cb26-8" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Vkll = 0.5*0.5*(Dl/Dk)*((Dk-Dl)/(Dk))</span>
<span id="cb26-9"><a href="#cb26-9" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> <span class="kw">post</span> i.unit i.<span class="fu">year</span></span>
<span id="cb26-10"><a href="#cb26-10" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> residuals, residuals</span>
<span id="cb26-11"><a href="#cb26-11" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> residuals2 = residuals^2</span>
<span id="cb26-12"><a href="#cb26-12" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> residuals2</span>
<span id="cb26-13"><a href="#cb26-13" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> VD = <span class="fu">r</span>(<span class="kw">mean</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The weights are thus the following:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wkU = ((nk + nu)^2*VkU)/VD</span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wkU</span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wlU = ((<span class="kw">nl</span> + nu)^2*VlU)/VD</span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wlU</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wklk = (((nk + <span class="kw">nl</span>)*(1-Dl))^2*Vklk)/VD</span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wklk</span>
<span id="cb27-7"><a href="#cb27-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wkll = (((nk + <span class="kw">nl</span>)*Dk)^2*Vkll)/VD</span>
<span id="cb27-8"><a href="#cb27-8" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wkll</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>.31818181


.36363635


.13636363


.18181817</code></pre>
</div>
</div>
<p>With this in mind the <span class="math inline">\(\tau\)</span> estimate is</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> tau = wkU * bku + wlU * blu + wklk * bklk + wkll * bkll</span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> tau</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>2.4545455</code></pre>
</div>
</div>
<p>as observed in the two-way fixed effect estimate above.</p>
</section>
</section>
<section id="b-decomposition-with-trends" class="level4">
<h4 class="anchored" data-anchor-id="b-decomposition-with-trends">(b) Decomposition with trends</h4>
<p>In this case the <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> decomposition follows as above generating the treatment effect as follows:</p>
<p><img src="docs/01_04_Chapter4R_files/figure-html/unnamed-chunk-22-1.png" class="img-fluid"></p>
<p>As seen in the plots, in the decomposition with trends these effects are no longer constants of 3 and 2 for early and later treated units given that the “treatment effect” is no longer simply <span class="math inline">\(1 \times unit\)</span> in each case.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>* 2x2 DD Regressions <span class="kw">for</span> betas</span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> y2 <span class="kw">post</span> i.<span class="fu">year</span> i.unit <span class="kw">if</span> unit != 2</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> bku = _b[<span class="kw">post</span>]</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> y2 <span class="kw">post</span> i.<span class="fu">year</span> i.unit <span class="kw">if</span> unit != 3</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> blu = _b[<span class="kw">post</span>]</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> y2 <span class="kw">post</span> i.<span class="fu">year</span> i.unit <span class="kw">if</span> unit != 1 &amp; <span class="fu">year</span> &lt; 2006</span>
<span id="cb31-7"><a href="#cb31-7" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> bklk = _b[<span class="kw">post</span>]</span>
<span id="cb31-8"><a href="#cb31-8" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> y2 <span class="kw">post</span> i.<span class="fu">year</span> i.unit <span class="kw">if</span> unit != 1 &amp; <span class="fu">year</span> &gt; 2002</span>
<span id="cb31-9"><a href="#cb31-9" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> bkll = _b[<span class="kw">post</span>]</span>
<span id="cb31-10"><a href="#cb31-10" aria-hidden="true" tabindex="-1"></a>* Share <span class="kw">of</span> time treated</span>
<span id="cb31-11"><a href="#cb31-11" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> <span class="kw">post</span> <span class="kw">if</span> unit == 3</span>
<span id="cb31-12"><a href="#cb31-12" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Dk = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb31-13"><a href="#cb31-13" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> <span class="kw">post</span> <span class="kw">if</span> unit == 2</span>
<span id="cb31-14"><a href="#cb31-14" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Dl = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb31-15"><a href="#cb31-15" aria-hidden="true" tabindex="-1"></a>* How much treatment varies</span>
<span id="cb31-16"><a href="#cb31-16" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> VkU = 0.5*0.5*(Dk)*(1-Dk)</span>
<span id="cb31-17"><a href="#cb31-17" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> VlU = 0.5*0.5*(Dl)*(1-Dl)</span>
<span id="cb31-18"><a href="#cb31-18" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Vklk = 0.5*0.5*((Dk-Dl)/(1-Dl))*((1-Dk)/(1-Dl))</span>
<span id="cb31-19"><a href="#cb31-19" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> Vkll = 0.5*0.5*(Dl/Dk)*((Dk-Dl)/(Dk))</span>
<span id="cb31-20"><a href="#cb31-20" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">reg</span> <span class="kw">post</span> i.unit i.<span class="fu">year</span></span>
<span id="cb31-21"><a href="#cb31-21" aria-hidden="true" tabindex="-1"></a><span class="kw">predict</span> residuals, residuals</span>
<span id="cb31-22"><a href="#cb31-22" aria-hidden="true" tabindex="-1"></a><span class="kw">gen</span> residuals2 = residuals^2</span>
<span id="cb31-23"><a href="#cb31-23" aria-hidden="true" tabindex="-1"></a><span class="kw">qui</span> <span class="kw">sum</span> residuals2</span>
<span id="cb31-24"><a href="#cb31-24" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> VD = <span class="fu">r</span>(<span class="kw">mean</span>)</span>
<span id="cb31-25"><a href="#cb31-25" aria-hidden="true" tabindex="-1"></a>* Share <span class="kw">of</span> <span class="kw">sample</span></span>
<span id="cb31-26"><a href="#cb31-26" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> nk = 1/3</span>
<span id="cb31-27"><a href="#cb31-27" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> <span class="kw">nl</span> = 1/3</span>
<span id="cb31-28"><a href="#cb31-28" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> nu = 1/3</span>
<span id="cb31-29"><a href="#cb31-29" aria-hidden="true" tabindex="-1"></a>* Weights</span>
<span id="cb31-30"><a href="#cb31-30" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wkU = ((nk + nu)^2*VkU)/VD</span>
<span id="cb31-31"><a href="#cb31-31" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wkU</span>
<span id="cb31-32"><a href="#cb31-32" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wlU = ((<span class="kw">nl</span> + nu)^2*VlU)/VD</span>
<span id="cb31-33"><a href="#cb31-33" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wlU</span>
<span id="cb31-34"><a href="#cb31-34" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wklk = (((nk + <span class="kw">nl</span>)*(1-Dl))^2*Vklk)/VD</span>
<span id="cb31-35"><a href="#cb31-35" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wklk</span>
<span id="cb31-36"><a href="#cb31-36" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> wkll = (((nk + <span class="kw">nl</span>)*Dk)^2*Vkll)/VD</span>
<span id="cb31-37"><a href="#cb31-37" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> wkll</span>
<span id="cb31-38"><a href="#cb31-38" aria-hidden="true" tabindex="-1"></a>* Tau</span>
<span id="cb31-39"><a href="#cb31-39" aria-hidden="true" tabindex="-1"></a><span class="fu">scalar</span> tau = wkU * bku + wlU * blu + wklk * bklk + wkll * bkll</span>
<span id="cb31-40"><a href="#cb31-40" aria-hidden="true" tabindex="-1"></a><span class="kw">di</span> tau</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>.31818181


.36363635


.13636363


.18181817


3.8045452</code></pre>
</div>
</div>
<p>What is noteworthy here is the surprising behaviour flagged by <span class="citation" data-cites="GoodmanBacon2018">Goodman-Bacon (<a href="06_references.html#ref-GoodmanBacon2018" role="doc-biblioref">2021</a>)</span> for the final comparison based on the case where the earlier treated unit (unit 3) is used as a control for the later trated unit (unit 2). In this case, given that there <em>are</em> time-varying treatment effects, despite the fact that each unit-specific treatment effect is positive, we observe that the parameter <span class="math inline">\(\widehat{\beta}^{2 \times 2, l}_{kl}\)</span> is actually <em>negative</em>. In this particular example this negative value (-1.375) is not sufficient to turn the weighted treatment effect estimate negative, but if you play around with the size of the parameters <span class="math inline">\(\beta_1\)</span> and <span class="math inline">\(\beta_2\)</span> above, you will see that large enough differences in trends <em>can</em> result in such estimates! Here, as above, we see that when we aggregate unit-specific estimates as <code>tau</code>, the estimate (by definition) agrees with the estimate generated by two-way fixed effect models previously.</p>
</section>
</section>
<section id="dechaisemartindhaultfoeuille2019s-procedure" class="level3">
<h3 class="anchored" data-anchor-id="dechaisemartindhaultfoeuille2019s-procedure"><span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (<a href="06_references.html#ref-deChaisemartinDhaultfoeuille2019" role="doc-biblioref">2020</a>)</span>’s Procedure</h3>
<p>Now, we will show that the procedures described in <span class="citation" data-cites="deChaisemartinDhaultfoeuille2019">Chaisemartin and D’Haultfoeuille (<a href="06_references.html#ref-deChaisemartinDhaultfoeuille2019" role="doc-biblioref">2020</a>)</span>, despite arriving to the estimator in a different way, also let us understand how the regression weights the two-way fixed effect estimator. In this case, rather than considering each treatment-control comparison pair, the authors note that the two-way fixed estimator can be conceived as a weighted sum of each single group by time period in any post-treatment group.</p>
<p>The authors define <span class="math inline">\(\widehat{\beta}_{fe}\)</span> as the coefficient estimated in the following (standard) two-way fixed effects regression: <span class="math display">\[y_{i,s,t} = \beta_0 + \beta_{fe} D_{s,t} + \mu_s + \lambda_t + \varepsilon_{s,t}\]</span> Where <span class="math inline">\(D_{s,t}\)</span> is the mean over <span class="math inline">\(i\)</span> of a binary indicator variable that takes value of 1 if the unit <span class="math inline">\(i\)</span> in state <span class="math inline">\(s\)</span> is treated at period <span class="math inline">\(t\)</span> and 0 otherwise, in our case as we have one observartion per state <span class="math inline">\(D_{s,t} = post_{s,t}\)</span>, meanwhile <span class="math inline">\(\mu_s\)</span> and <span class="math inline">\(\lambda_t\)</span> are state and time fixed effects. This is, of course, precisely the same model as we have estimated in <a href="03_04_Chapter4Python.html#eq-twfe">Equation&nbsp;<span>14.1</span></a>, implying that <span class="math inline">\(\beta_{fe}=2.4545\)</span> in cases without post-treatment trends (<code>y1</code>), or <span class="math inline">\(\beta_{fe}=3.8045\)</span> in cases with post-treatment dynamics (<code>y2</code>).</p>
</section>
</section>
<section id="synthetic-control-exercise" class="level2">
<h2 class="anchored" data-anchor-id="synthetic-control-exercise">Synthetic Control Exercise</h2>
<p>The synthetic control method seeks to construct a “synthetic control” for a treated unit (in this case, California) using a weighted combination of control units (other states). The aim is for this synthetic control to closely resemble the treated unit in the pre-treatment period based on predictor variables.</p>
<ul>
<li>Use the ‘synth’ command to construct the synthetic control for California</li>
<li>Predictor variables: cigsale from specific years, beer, lnincome, retprice, age15to24</li>
<li>Treated unit: California (state==3)</li>
<li>Treatment period: 1989</li>
<li>Periods used to construct the synthetic control: 1980-1988</li>
</ul>
<p>Once the synthetic control is constructed, we can compare the trends of the treated unit and the synthetic control in the post-treatment period. Any divergence in trends is interpreted as the treatment effect. In this case, we are assessing the impact of a hypothetical policy implemented in California in 1989 on cigarette sales.</p>
<div class="cell">

</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>* Clear the workspace and turn <span class="kw">off</span> result pagination</span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a><span class="kw">clear</span> <span class="ot">all</span></span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a><span class="kw">set</span> <span class="kw">more</span> <span class="kw">off</span></span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>* Install the 'synth' package <span class="kw">if</span> <span class="kw">not</span> already installed</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>*<span class="kw">ssc</span> install synth, <span class="kw">replace</span></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>* Load the dataset 'smoking.dta'</span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="kw">insheet</span> <span class="kw">using</span> <span class="st">"Datasets/Abadie_data.csv"</span>, <span class="kw">comma</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>* Set the <span class="kw">data</span> <span class="kw">as</span> panel <span class="kw">data</span> with 'state' <span class="kw">as</span> the panel unit and 'year' <span class="kw">as</span> the time <span class="kw">variable</span></span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a><span class="kw">tsset</span> state <span class="fu">year</span></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>* The synthetic control method seeks to construct a <span class="st">"synthetic control"</span> <span class="kw">for</span> a treated unit (<span class="kw">in</span> <span class="kw">this</span> <span class="kw">case</span>, California) <span class="kw">using</span> a weighted combination <span class="kw">of</span> control units (other states). The aim is <span class="kw">for</span> <span class="kw">this</span> synthetic control to closely resemble the treated unit <span class="kw">in</span> the pre-treatment period based <span class="kw">on</span> predictor variables.</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-16"><a href="#cb33-16" aria-hidden="true" tabindex="-1"></a>* Use the 'synth' command to construct the synthetic control <span class="kw">for</span> California</span>
<span id="cb33-17"><a href="#cb33-17" aria-hidden="true" tabindex="-1"></a>* - Predictor variables: cigsale from specific years, beer, lnincome, retprice, age15to24</span>
<span id="cb33-18"><a href="#cb33-18" aria-hidden="true" tabindex="-1"></a>* - Treated unit: California (state==3)</span>
<span id="cb33-19"><a href="#cb33-19" aria-hidden="true" tabindex="-1"></a>* - Treatment period: 1989</span>
<span id="cb33-20"><a href="#cb33-20" aria-hidden="true" tabindex="-1"></a>* - Periods used to construct the synthetic control: 1980-1988</span>
<span id="cb33-21"><a href="#cb33-21" aria-hidden="true" tabindex="-1"></a>synth cigsale beer lnincome retprice age15to24 cigsale(1988) cigsale(1980) cigsale(1975), <span class="co">///</span></span>
<span id="cb33-22"><a href="#cb33-22" aria-hidden="true" tabindex="-1"></a>      trunit(3) trperiod(1989) xperiod(1980(1)1988) nested fig <span class="kw">keep</span>(results) <span class="kw">replace</span></span>
<span id="cb33-23"><a href="#cb33-23" aria-hidden="true" tabindex="-1"></a>      </span>
<span id="cb33-24"><a href="#cb33-24" aria-hidden="true" tabindex="-1"></a><span class="kw">use</span> results.dta, <span class="kw">clear</span></span>
<span id="cb33-25"><a href="#cb33-25" aria-hidden="true" tabindex="-1"></a><span class="kw">tsset</span> _time</span>
<span id="cb33-26"><a href="#cb33-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-27"><a href="#cb33-27" aria-hidden="true" tabindex="-1"></a>* Create the <span class="kw">graph</span> with a dotted <span class="kw">line</span> <span class="fu">at</span> the treatment period</span>
<span id="cb33-28"><a href="#cb33-28" aria-hidden="true" tabindex="-1"></a><span class="kw">twoway</span> (<span class="kw">tsline</span> _Y_treated _Y_synthetic, graphregion(<span class="kw">color</span>(<span class="bn">white</span>)) lcolor(<span class="bn">blue</span> <span class="kw">red</span>) <span class="co">///</span></span>
<span id="cb33-29"><a href="#cb33-29" aria-hidden="true" tabindex="-1"></a>    <span class="bn">title</span>(<span class="st">"Cigarette Sales in California vs. Synthetic Control"</span>) <span class="co">///</span></span>
<span id="cb33-30"><a href="#cb33-30" aria-hidden="true" tabindex="-1"></a>    <span class="bn">legend</span>(<span class="kw">label</span>(1 <span class="st">"California"</span>) <span class="kw">label</span>(2 <span class="st">"Synthetic California"</span>) <span class="kw">order</span>(1 2 3))) <span class="co">///</span></span>
<span id="cb33-31"><a href="#cb33-31" aria-hidden="true" tabindex="-1"></a>    (<span class="kw">function</span> <span class="fu">y</span> = _Y_treated, <span class="kw">range</span>(1989 1989) lpattern(<span class="kw">dash</span>) lcolor(gs8) <span class="bn">legend</span>(<span class="kw">label</span>(3 <span class="st">"Tobacco Policy Change (1989)"</span>))), <span class="co">///</span></span>
<span id="cb33-32"><a href="#cb33-32" aria-hidden="true" tabindex="-1"></a>    <span class="bn">ytitle</span>(<span class="st">"Cigarette Sales"</span>) <span class="bn">xtitle</span>(<span class="st">"Year"</span>)</span>
<span id="cb33-33"><a href="#cb33-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-34"><a href="#cb33-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-35"><a href="#cb33-35" aria-hidden="true" tabindex="-1"></a>* Once the synthetic control is constructed, we can <span class="kw">compare</span> the trends <span class="kw">of</span> the treated unit and the synthetic control <span class="kw">in</span> the <span class="kw">post</span>-treatment period. Any divergence <span class="kw">in</span> trends is interpreted <span class="kw">as</span> the treatment effect. In <span class="kw">this</span> <span class="kw">case</span>, we are assessing the impact <span class="kw">of</span> a hypothetical policy implemented <span class="kw">in</span> California <span class="kw">in</span> 1989 <span class="kw">on</span> cigarette sales.</span>
<span id="cb33-36"><a href="#cb33-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-37"><a href="#cb33-37" aria-hidden="true" tabindex="-1"></a>* Results:</span>
<span id="cb33-38"><a href="#cb33-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-39"><a href="#cb33-39" aria-hidden="true" tabindex="-1"></a>* 1. The synthetic control <span class="kw">for</span> California is constructed <span class="kw">using</span> a combination <span class="kw">of</span> other states. Specifically, weights are assigned to states like Colorado, Connecticut, Montana, Nevada, New Mexico, and Utah.</span>
<span id="cb33-40"><a href="#cb33-40" aria-hidden="true" tabindex="-1"></a>* 2. The RMSPE (Root Mean Squared Prediction Error) is a measure <span class="kw">of</span> how well the synthetic control approximates California <span class="kw">in</span> the pre-treatment period. A <span class="fu">lower</span> RMSPE indicates a better <span class="kw">fit</span>. In <span class="kw">this</span> <span class="kw">case</span>, the RMSPE is 1.756235, suggesting a reasonably good <span class="kw">fit</span>.</span>
<span id="cb33-41"><a href="#cb33-41" aria-hidden="true" tabindex="-1"></a>* 3. The <span class="st">"Predictor Balance"</span> <span class="kw">table</span> shows how California and the synthetic control <span class="kw">compare</span> <span class="kw">in</span> terms <span class="kw">of</span> the predictor variables. The figures show that there is a good balance between the treated unit and the synthetic control <span class="kw">on</span> these variables.</span>
<span id="cb33-42"><a href="#cb33-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-43"><a href="#cb33-43" aria-hidden="true" tabindex="-1"></a>* The <span class="kw">graph</span> displays per capita cigarette sales <span class="kw">in</span> California and the synthetic control <span class="bn">over</span> time. The divergence between the <span class="kw">two</span> lines <span class="kw">post</span>-1989 represents the estimated effect <span class="kw">of</span> the policy.</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>(8 vars, 1,209 obs)

       panel variable:  state (strongly balanced)
        time variable:  year, 1970 to 2000
                delta:  1 unit

command synth is unrecognized
r(199);

end of do-file
r(199);</code></pre>
</div>
</div>


<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography" style="display: none">
<div id="ref-AtheyImbens2018" class="csl-entry" role="doc-biblioentry">
Athey, Susan, and Guido W. Imbens. 2022. <span>“<span class="nocase">Design-based analysis in Difference-In-Differences settings with staggered adoption</span>.”</span> <em>Journal of Econometrics</em> 226 (1): 62–79. https://doi.org/<a href="https://doi.org/10.1016/j.jeconom.2020.10.012">https://doi.org/10.1016/j.jeconom.2020.10.012</a>.
</div>
<div id="ref-deChaisemartinDhaultfoeuille2019" class="csl-entry" role="doc-biblioentry">
Chaisemartin, Clément de, and Xavier D’Haultfoeuille. 2020. <span>“Two-Way Fixed Effects Estimators with Heterogeneous Treatment Effects.”</span> <em>American Economic Review</em> 110 (9): 2964–96. <a href="https://doi.org/10.1257/aer.20181169">https://doi.org/10.1257/aer.20181169</a>.
</div>
<div id="ref-GoodmanBacon2018" class="csl-entry" role="doc-biblioentry">
Goodman-Bacon, Andrew. 2021. <span>“Difference-in-Differences with Variation in Treatment Timing.”</span> <em>Journal of Econometrics</em> 225 (2): 254–77. https://doi.org/<a href="https://doi.org/10.1016/j.jeconom.2021.03.014">https://doi.org/10.1016/j.jeconom.2021.03.014</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./02_03_Chapter3Stata.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Chapter 3</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./03_00_FollowingPython.html" class="pagination-link">
        <span class="nav-page-text">Following Along with Python</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>